/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Sql;

/**
 *
 * @author David
 */
public enum SqlStatement {
    CreateDatabase("CREATE DATABASE `%s`;", "CREATE DATABASE %s;", "CREATE DATABASE `%s`;", "CREATE DATABASE `%s`;"),
    CreateTable("CREATE TABLE `%s` (", "CREATE TABLE %s (", "CREATE TABLE `%s` (", ""),
    EndCreateTable(");", ");", ");", ""),
    addRow("`%s`", "%s", "`%s`", ""),
    Insert("INSERT INTO `%s` (", "INSERT INTO %s (", "INSERT INTO `%s` (", ""),
    EndInsert(")", ")", ")", ""),
    InsertColumn("`%s`", "%s", "", ""),
    InsertValues("VALUES ", "VALUES ", "VALUES ", ""),
    EndofInsertValues(");", ");", ");", ""),
    InsertValue("`%s`", "'%s'", "`%s`", ""),
    EndofInsertValue("),", "),", "),", ""),
    NotNull("NOT NULL", "NOT NULL", "NOT NULL", ""),
    IsNull("NULL", "NULL", "NULL", ""),
    PrimaryKey("PRIMARY KEY", "CONSTRAINT PK_%s PRIMARY KEY(%s);", "PRIMARY KEY (`%s`)", ""),
    ForeignKey("FOREIGN KEY (id_%s) REFERENCES %s(id_%s)",
            "CONSTRAINT %s_fk\n FOREIGN KEY (id_%s)\n REFERENCES %s(id_%s)",
            "CONSTRAINT %s_fk FOREIGN KEY (id_%s) REFERENCES %s (id_%s)",
            ""),
    AutoIncrement("AUTO_INCREMENT", "GENERATED BY DEFAULT ON NULL AS IDENTITY", "identity(1, 1)", ""),
    StringText("VARCHAR(%s)","VARCHAR2(%s)","varchar(%s)",""),
    IntNumber("INT", "INT", "int", ""),
    UnsignedIntNumber("INT UNSIGNED", "INT", "int", ""),
    LongNumber("BIG INT", "INT", "bigint", ""),
    UnsignedLongNumber("BIG INT UNSIGNED", "INT", "bigint", ""),
    FloatNumber("FLOAT", "FLOAT", "float", ""),
    Url("VARCHAR(65535)", "VARCHAR2(32767)", "varchar(max)", ""),
    Timestamp("TIMESTAMP","TIMESTAMP","datetime2",""),// mySql(YYYY-MM-DD HH:MM:SS[.fraction]), oracle(YYYY-MM-DD HH:MM:SS), microsoft(YYYY-MM-DD hh:mm:ss[.fractional seconds])
    Date("DATE","DATE","date",""); // mySql(YYYY-MM-DD), oracle('DD-MM-YYYY'), microsoft('YYYY-MM-DD')
    
    
    private final String mySqlStatement;
    private final String oracleStatement;
    private final String microsoftStatement;
    private final String accessStatement;

    private SqlStatement(String mySqlStatement, String oracleStatement, String microsoftStatement, String accessStatement) {
        this.mySqlStatement = mySqlStatement;
        this.oracleStatement = oracleStatement;
        this.microsoftStatement = microsoftStatement;
        this.accessStatement = accessStatement;
    }
    


    public String getStatement(DatabaseType dbType) {
        switch (dbType) {
            case MySql:
                return mySqlStatement;
            
            case Oracle:
                return oracleStatement;
            
            case Microsoft:
                return microsoftStatement;
            
            case Access:
                return accessStatement;
            
            default: 
                return null;
        }
    }
}
